version: {{ .Version }}
name: {{ .Name }}
author: {{ .Author }}
email: {{ .Email }}
git: {{ .Repository }}
description: {{ .Description }}
application: {{ .Application }}
destination: {{ .Destination }}
with_config: {{ .WithConfiguration }}
